export default [
    {
      kodeBarang: "BRG-112",
      namaBarang: "Kotak Pandora",
      hargaBeli: 7000,
      hargaJual: 7400,
      jumlahBarang: 200,
    },
    {
      kodeBarang: "BRG-111",
      namaBarang: "Kotak Pandora",
      hargaBeli: 7000,
      hargaJual: 7400,
      jumlahBarang: 200,
    },
    {
      kodeBarang: "BRG-101",
      namaBarang: "Kotak Pandora",
      hargaBeli: 7000,
      hargaJual: 7400,
      jumlahBarang: 200,
    },
    {
      kodeBarang: "BRG-1",
      namaBarang: "Kotak Pandora",
      hargaBeli: 7000,
      hargaJual: 7400,
      jumlahBarang: 200,
    },
    {
      kodeBarang: "BRG-006",
      namaBarang: "Krisbow Battery A2",
      hargaBeli: 7000,
      hargaJual: 7400,
      jumlahBarang: 200,
    },
    {
      kodeBarang: "BRG-005",
      namaBarang: "Yupi Candy Bear",
      hargaBeli: 920,
      hargaJual: 1000,
      jumlahBarang: 120,
    },
    {
      kodeBarang: "BRG-004",
      namaBarang: "Happy Care Hand Sanitizer",
      hargaBeli: 12000,
      hargaJual: 15000,
      jumlahBarang: 98,
    },
    {
      kodeBarang: "BRG-002",
      namaBarang: "Dompet Nevergate",
      hargaBeli: 14000,
      hargaJual: 23000,
      jumlahBarang: 166,
    },
  ];